/**
 * Seed fixtures. Coordinates are real Mumbai localities so the geospatial
 * queries return believable distances rather than points on a grid.
 */

export const ZONES = [
  { zone: 'Andheri West', city: 'Mumbai', pincode: '400058', center: [72.8296, 19.1364] },
  { zone: 'Bandra West', city: 'Mumbai', pincode: '400050', center: [72.8296, 19.0596] },
  { zone: 'Powai', city: 'Mumbai', pincode: '400076', center: [72.9051, 19.1176] },
  { zone: 'Dadar', city: 'Mumbai', pincode: '400028', center: [72.8420, 19.0176] },
  { zone: 'Malad West', city: 'Mumbai', pincode: '400064', center: [72.8484, 19.1868] },
  { zone: 'Chembur', city: 'Mumbai', pincode: '400071', center: [72.8998, 19.0522] },
  { zone: 'Thane West', city: 'Thane', pincode: '400601', center: [72.9781, 19.2183] },
  { zone: 'Goregaon East', city: 'Mumbai', pincode: '400063', center: [72.8656, 19.1663] },
];

export const COOPERATIVES = [
  {
    name: 'Westline Home Services',
    code: 'WHS',
    registrationNo: 'U74999MH2019PTC044120',
    city: 'Mumbai',
    state: 'Maharashtra',
    foundedYear: 2019,
    about:
      'Electricians, plumbers, carpenters and cleaners across the western suburbs, all identity-verified and background-checked before their first job.',
    location: { type: 'Point', coordinates: [72.8479, 19.0896] },
    contact: { phone: '9820011223', email: 'support@westlinehome.in' },
    governance: {
      commissionPct: 0.08,
      minHourlyRate: 200,
      surgeCeiling: 1.6,
    },
    trainingPrograms: [
      { name: 'Certified Home Wiring', skill: 'electrician', durationHours: 40, certified: true },
      { name: 'Modern Fixtures & Leak Detection', skill: 'plumber', durationHours: 24, certified: true },
      { name: 'Customer Handling & Safety', skill: 'all', durationHours: 8, certified: false },
    ],
  },
  {
    name: 'Northgate Facility Care',
    code: 'NFC',
    registrationNo: 'U74999MH2021PTC077310',
    city: 'Thane',
    state: 'Maharashtra',
    foundedYear: 2021,
    about:
      'A multi-trade home-services company operating across Thane, running its own skills academy and an in-house quality audit on every job.',
    location: { type: 'Point', coordinates: [72.9781, 19.2183] },
    contact: { phone: '9930044556', email: 'care@northgatefacility.in' },
    governance: {
      commissionPct: 0.07,
      minHourlyRate: 180,
      surgeCeiling: 1.5,
    },
    trainingPrograms: [
      { name: 'Deep Cleaning Certification', skill: 'cleaner', durationHours: 16, certified: true },
      { name: 'Appliance Repair Basics', skill: 'appliance_tech', durationHours: 32, certified: true },
    ],
  },
];

export const SERVICES = [
  {
    name: 'Electrician',
    slug: 'electrician',
    category: 'Home Repair',
    skillTag: 'electrician',
    tagline: 'Wiring, switches, fans and fault-finding',
    description:
      'Certified electricians for everything from a tripping MCB to a full room rewiring. All members carry a coop-issued safety certification.',
    icon: 'zap',
    heroColor: 'saffron',
    basePrice: 349,
    baseDurationMins: 60,
    emergencyAvailable: true,
    emergencySurcharge: 150,
    displayOrder: 1,
    checklist: [
      'Isolate the circuit at the mains before work',
      'Test earthing and load before restoring supply',
      'Show the customer the fault and the fix',
      'Clear all debris from the work area',
    ],
    equipment: ['Multimeter', 'Insulated tools', 'Test lamp', 'Ladder'],
    packages: [
      {
        name: 'Quick Fix Visit',
        slug: 'quick-fix',
        description: 'One fault, diagnosed and repaired',
        price: 349,
        durationMins: 45,
        includes: ['Diagnosis', 'Minor repair', 'Basic consumables'],
        excludes: ['Replacement parts'],
        popular: true,
      },
      {
        name: 'Full Home Inspection',
        slug: 'home-inspection',
        description: 'Every circuit, board and earthing point checked',
        price: 899,
        durationMins: 120,
        includes: ['Load analysis', 'Earthing test', 'Written safety report'],
      },
      {
        name: 'Fan / Light Installation',
        slug: 'fixture-install',
        description: 'Up to 3 fixtures mounted and wired',
        price: 599,
        durationMins: 90,
        includes: ['Mounting', 'Wiring', 'Testing'],
      },
    ],
  },
  {
    name: 'Plumber',
    slug: 'plumber',
    category: 'Home Repair',
    skillTag: 'plumber',
    tagline: 'Leaks, blockages, taps and fittings',
    description:
      'Leak detection, drain clearing and sanitary-ware installation by members trained on modern fittings.',
    icon: 'droplet',
    heroColor: 'navy',
    basePrice: 299,
    baseDurationMins: 60,
    emergencyAvailable: true,
    emergencySurcharge: 200,
    displayOrder: 2,
    checklist: [
      'Shut off the supply line before opening any fitting',
      'Protect flooring and fittings with sheeting',
      'Pressure-test the joint before closing up',
      'Leave the area dry and clean',
    ],
    equipment: ['Pipe wrench', 'Drain auger', 'Leak detector', 'Sealant'],
    packages: [
      {
        name: 'Leak Repair',
        slug: 'leak-repair',
        description: 'Trace and seal one leak',
        price: 299,
        durationMins: 45,
        includes: ['Leak tracing', 'Sealing', 'Pressure test'],
        popular: true,
      },
      {
        name: 'Drain Unblocking',
        slug: 'drain-unblock',
        description: 'Machine-cleared blockage, up to 2 points',
        price: 549,
        durationMins: 60,
        includes: ['Machine clearing', 'Flow test'],
      },
      {
        name: 'Bathroom Fitting Install',
        slug: 'bathroom-fitting',
        description: 'Taps, shower or health faucet installed',
        price: 699,
        durationMins: 90,
        includes: ['Removal of old fitting', 'Installation', 'Testing'],
        excludes: ['The fitting itself'],
      },
    ],
  },
  {
    name: 'Deep Cleaning',
    slug: 'deep-cleaning',
    category: 'Cleaning',
    skillTag: 'cleaner',
    tagline: 'Kitchens, bathrooms and full-home cleaning',
    description:
      'Trained cleaning crews using coop-supplied equipment and non-toxic chemicals. Priced per home size, never per hour.',
    icon: 'sparkles',
    heroColor: 'coop',
    basePrice: 1499,
    baseDurationMins: 240,
    emergencyAvailable: false,
    displayOrder: 3,
    checklist: [
      'Photograph the space before starting',
      'Work top-down, room by room',
      'Use only the approved chemical set',
      'Walk the customer through each room at the end',
    ],
    equipment: ['Vacuum', 'Steam cleaner', 'Microfibre set', 'Approved chemicals'],
    packages: [
      {
        name: '1 BHK Deep Clean',
        slug: '1bhk',
        description: 'Full home, 2 cleaners',
        price: 1499,
        durationMins: 240,
        includes: ['Kitchen degreasing', 'Bathroom descaling', 'Floors', 'Windows'],
        popular: true,
      },
      {
        name: '2 BHK Deep Clean',
        slug: '2bhk',
        description: 'Full home, 3 cleaners',
        price: 2299,
        durationMins: 300,
        includes: ['Kitchen degreasing', 'Bathroom descaling', 'Floors', 'Windows', 'Balcony'],
      },
      {
        name: 'Kitchen Only',
        slug: 'kitchen',
        description: 'Cabinets, chimney, tiles and appliances',
        price: 899,
        durationMins: 150,
        includes: ['Chimney degreasing', 'Cabinet interiors', 'Tile scrubbing'],
      },
    ],
  },
  {
    name: 'AC Service & Repair',
    slug: 'ac-service',
    category: 'Appliances',
    skillTag: 'appliance_tech',
    tagline: 'Servicing, gas refill and installation',
    description: 'Split and window AC servicing by technicians certified on all major brands.',
    icon: 'wind',
    heroColor: 'navy',
    basePrice: 599,
    baseDurationMins: 75,
    emergencyAvailable: true,
    emergencySurcharge: 250,
    displayOrder: 4,
    checklist: [
      'Record the inlet and outlet temperature before service',
      'Clean coils, filters and drain line',
      'Check gas pressure and log the reading',
      'Show the before/after cooling difference',
    ],
    equipment: ['Jet pump', 'Gauge manifold', 'Fin comb', 'Drop sheet'],
    packages: [
      {
        name: 'Standard Service',
        slug: 'standard-service',
        description: 'One split or window unit',
        price: 599,
        durationMins: 75,
        includes: ['Coil cleaning', 'Filter wash', 'Drain clearing', 'Cooling test'],
        popular: true,
      },
      {
        name: 'Gas Refill',
        slug: 'gas-refill',
        description: 'Leak check and full gas charge',
        price: 2499,
        durationMins: 120,
        includes: ['Leak test', 'Vacuuming', 'Gas charge', 'Performance test'],
      },
      {
        name: 'Installation / Uninstallation',
        slug: 'install',
        description: 'Mounting, piping and commissioning',
        price: 1799,
        durationMins: 150,
        includes: ['Bracket mounting', 'Piping up to 3m', 'Commissioning'],
      },
    ],
  },
  {
    name: 'Carpenter',
    slug: 'carpenter',
    category: 'Home Repair',
    skillTag: 'carpenter',
    tagline: 'Furniture repair, fittings and custom work',
    description: 'Door alignment, hinge and lock replacement, shelving and furniture assembly.',
    icon: 'hammer',
    heroColor: 'saffron',
    basePrice: 449,
    baseDurationMins: 90,
    emergencyAvailable: false,
    displayOrder: 5,
    checklist: [
      'Confirm measurements with the customer before cutting',
      'Sheet the floor before any sawing',
      'Vacuum sawdust before leaving',
    ],
    equipment: ['Cordless drill', 'Chisel set', 'Spirit level', 'Measuring tape'],
    packages: [
      {
        name: 'Repair Visit',
        slug: 'repair',
        description: 'Hinges, handles, drawer runners',
        price: 449,
        durationMins: 60,
        includes: ['Diagnosis', 'Repair', 'Hardware adjustment'],
        popular: true,
      },
      {
        name: 'Furniture Assembly',
        slug: 'assembly',
        description: 'Flat-pack assembled and levelled',
        price: 699,
        durationMins: 120,
        includes: ['Assembly', 'Levelling', 'Packaging disposal'],
      },
    ],
  },
  {
    name: 'Painter',
    slug: 'painter',
    category: 'Home Improvement',
    skillTag: 'painter',
    tagline: 'Interior painting and touch-ups',
    description: 'Room repainting, waterproofing and putty work with coop-negotiated material rates.',
    icon: 'paint-roller',
    heroColor: 'coop',
    basePrice: 2999,
    baseDurationMins: 480,
    emergencyAvailable: false,
    displayOrder: 6,
    checklist: [
      'Mask and sheet all furniture and fittings',
      'Confirm the exact shade code with the customer',
      'Two coats minimum, with drying time between',
      'Remove all masking and clean up',
    ],
    equipment: ['Rollers', 'Masking sheets', 'Sanding block', 'Ladder'],
    packages: [
      {
        name: 'Single Room',
        slug: 'single-room',
        description: 'Up to 120 sq ft, two coats',
        price: 2999,
        durationMins: 480,
        includes: ['Putty and sanding', 'Primer', 'Two coats'],
        excludes: ['Paint material'],
        popular: true,
      },
      {
        name: 'Touch-up Visit',
        slug: 'touch-up',
        description: 'Patch repairs and spot painting',
        price: 999,
        durationMins: 180,
        includes: ['Patch filling', 'Spot painting'],
      },
    ],
  },
  {
    name: 'Pest Control',
    slug: 'pest-control',
    category: 'Cleaning',
    skillTag: 'pest_control',
    tagline: 'Cockroach, termite and general treatment',
    description: 'Licensed treatment with child- and pet-safe chemicals, plus a 30-day warranty.',
    icon: 'bug',
    heroColor: 'navy',
    basePrice: 1199,
    baseDurationMins: 120,
    emergencyAvailable: false,
    displayOrder: 7,
    checklist: [
      'Confirm no children or pets in the treated area',
      'Record the chemical batch number',
      'Explain the re-entry waiting period',
    ],
    equipment: ['Sprayer', 'PPE kit', 'Gel applicator'],
    packages: [
      {
        name: 'General Pest Treatment',
        slug: 'general',
        description: 'Cockroach, ant and spider treatment',
        price: 1199,
        durationMins: 120,
        includes: ['Gel application', 'Spray treatment', '30-day warranty'],
        popular: true,
      },
      {
        name: 'Termite Treatment',
        slug: 'termite',
        description: 'Drill-and-fill for affected areas',
        price: 3499,
        durationMins: 240,
        includes: ['Inspection', 'Drill and fill', '1-year warranty'],
      },
    ],
  },
  {
    name: 'Home Tutor',
    slug: 'home-tutor',
    category: 'Education',
    skillTag: 'tutor',
    tagline: 'School subjects, classes 5 to 12',
    description: 'Verified tutors from the cooperative education wing, paid a living wage per session.',
    icon: 'book-open',
    heroColor: 'coop',
    basePrice: 499,
    unit: 'per_hour',
    baseDurationMins: 60,
    emergencyAvailable: false,
    displayOrder: 8,
    checklist: ['Share a session plan before starting', 'Leave a short progress note for the parent'],
    equipment: ['Whiteboard', 'Practice worksheets'],
    packages: [
      {
        name: 'Single Session',
        slug: 'single',
        description: 'One hour, one subject',
        price: 499,
        durationMins: 60,
        includes: ['Session plan', 'Progress note'],
        popular: true,
      },
      {
        name: 'Weekly Pack',
        slug: 'weekly',
        description: 'Four sessions a week',
        price: 1799,
        durationMins: 60,
        includes: ['4 sessions', 'Worksheets', 'Monthly report'],
      },
    ],
  },
];

/** Worker name pool, split by trade so the seed reads plausibly. */
export const WORKER_NAMES = {
  electrician: ['Ramesh Patil', 'Suresh Yadav', 'Imran Shaikh', 'Vijay Kamble', 'Anil Gupta', 'Sachin More'],
  plumber: ['Mahesh Jadhav', 'Rafiq Ansari', 'Ganesh Sawant', 'Dinesh Kumar', 'Prakash Rane'],
  cleaner: ['Sunita Devi', 'Lakshmi Nair', 'Rekha Bhosale', 'Fatima Sheikh', 'Manju Yadav', 'Kavita Salunkhe'],
  appliance_tech: ['Nitin Deshmukh', 'Arif Khan', 'Santosh Pawar', 'Rahul Tiwari'],
  carpenter: ['Bhaskar Naik', 'Salim Qureshi', 'Ravi Shetty', 'Deepak Mistry'],
  painter: ['Kishore Waghmare', 'Javed Mansuri', 'Sanjay Chavan'],
  pest_control: ['Pravin Gaikwad', 'Ashok Mane'],
  tutor: ['Priya Menon', 'Aisha Qureshi', 'Neha Kulkarni', 'Rohit Sharma'],
};

export const REVIEW_COMMENTS = [
  'Arrived on time and explained the problem clearly before starting.',
  'Very neat work, cleaned up everything afterwards.',
  'Fixed in twenty minutes what two other people could not.',
  'Polite and professional. Fair price, no hidden charges.',
  'Good work overall, though he arrived about half an hour late.',
  'Knew exactly what was wrong straight away. Would book again.',
  'Brought all his own tools and finished ahead of the estimate.',
  'Solid job. Explained how to avoid the same issue next time.',
];
